name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex python3-pip
          pip3 install pandoc-include
      
      - name: Build HTML files
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in root: $(ls)"
          echo "Does include.lua exist: $(ls $GITHUB_WORKSPACE/include.lua)"
          pandoc index.md \
            --standalone \
            -o index.html
          for f in */index.md; do
            echo "Processing: $f"
            pandoc "$f" \
              --lua-filter $GITHUB_WORKSPACE/include.lua \
              --standalone \
              -o "${f%.md}.html"
          done
      
      - name: Build PDF files
        run: |
          for f in */index.md; do
            pandoc "$f" \
              --lua-filter $GITHUB_WORKSPACE/include.lua \
              --pdf-engine=xelatex \
              -o "${f%/index.md}-syllabus.pdf"
          done
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
